### ISSUE TITLE
Enable for all file types

### ISSUE THREAD

**Issue by WhyNotHugo** [fszymanski/deoplete-emoji#12]
I'm trying to enable this for **all** file types.

I tried `call deoplete#custom#source('emoji', 'filetypes', ['*'])`, but `*` doesn't seem to work as I expected it to.

Any suggestions?

**Comment by fszymanski** [comment]
Empty list `call deoplete#custom#source('emoji', 'filetypes', [])`

**Comment by WhyNotHugo** [comment]
Oh, sorry for the lack of feedback! It works perfect, thanks!
