### ISSUE TITLE
Emojis Are Black

### ISSUE THREAD

**Issue by weilbith** [fszymanski/deoplete-emoji#4]
When I install this plugin and start typing a emoji name, the part where the preview should been shown is black and I can't see them. Do I need some specific font here? I use NerdFont...

![deopleteemoji](https://user-images.githubusercontent.com/12543647/41232406-8d689a50-6d86-11e8-99de-66056a5d5f7e.png)

**Comment by ezpuzz** [comment]
https://github.com/ezpuzz/deoplete-emoji/tree/submodule-emojis fixed in my branch here

**Comment by weilbith** [comment]
@ezpuzz sounds cool! :+1: 
Will give it a try soon. :)
